// Import paths via Webpack
export const Assets = {
  coast: {
    bg: require("../../sprites/bg.png"),
    1: require("../../sprites/coast/1.png"),
    2: require("../../sprites/coast/2.png"),
    3: require("../../sprites/coast/3.png"),
    4: require("../../sprites/coast/4.png"),
    5: require("../../sprites/coast/5.png"),
    6: require("../../sprites/coast/6.png"),
    7: require("../../sprites/coast/7.png"),
    8: require("../../sprites/coast/8.png"),
    9: require("../../sprites/coast/9.png"),
  },
  fractal1: {
    bg: require("../../sprites/bg.png"),
    1: require("../../sprites/fractal/1/1.jpg"),
    2: require("../../sprites/fractal/1/2.jpg"),
    3: require("../../sprites/fractal/1/3.jpg"),
    4: require("../../sprites/fractal/1/4.jpg"),
    5: require("../../sprites/fractal/1/5.jpg"),
    6: require("../../sprites/fractal/1/6.jpg"),
    7: require("../../sprites/fractal/1/7.jpg"),
    8: require("../../sprites/fractal/1/8.jpg"),
    9: require("../../sprites/fractal/1/9.jpg"),
  },
  fractal2: {
    bg: require("../../sprites/bg.png"),
    1: require("../../sprites/fractal/2/1.jpg"),
    2: require("../../sprites/fractal/2/2.jpg"),
    3: require("../../sprites/fractal/2/3.jpg"),
    4: require("../../sprites/fractal/2/4.jpg"),
    5: require("../../sprites/fractal/2/5.jpg"),
    6: require("../../sprites/fractal/2/6.jpg"),
    7: require("../../sprites/fractal/2/7.jpg"),
    8: require("../../sprites/fractal/2/8.jpg"),
    9: require("../../sprites/fractal/2/9.jpg"),
  },
  fractal3: {
    bg: require("../../sprites/bg.png"),
    1: require("../../sprites/fractal/3/1.jpg"),
    2: require("../../sprites/fractal/3/2.jpg"),
    3: require("../../sprites/fractal/3/3.jpg"),
    4: require("../../sprites/fractal/3/4.jpg"),
    5: require("../../sprites/fractal/3/5.jpg"),
    6: require("../../sprites/fractal/3/6.jpg"),
    7: require("../../sprites/fractal/3/7.jpg"),
    8: require("../../sprites/fractal/3/8.jpg"),
    9: require("../../sprites/fractal/3/9.jpg"),
  },
};
